### ISSUE TITLE
论文-R3Net: Recurrent Residual Refinement Network for Saliency Detection

### ISSUE THREAD

**Issue by LarT2P** [lartpang/Machine-Deep-Learning#38]
![image](https://user-images.githubusercontent.com/16298490/50723444-b1b7a280-1118-11e9-8f10-b40985409996.png)

![image](https://user-images.githubusercontent.com/16298490/50723448-c005be80-1118-11e9-8758-43c76e53c44c.png)

**Comment by LarT2P** [comment]
1. 使用ResNeXt提取特征, 分成了五个阶段
2. 使用前三个阶段产生的特征图上采样到输入图片的四分之一后拼接在一起, 卷积融合并减少特征数,产生低级融合特征
![image](https://user-images.githubusercontent.com/16298490/50723476-44584180-1119-11e9-8a90-525bd670c71c.png)
```python
# followed by 3 PReLU activation functions[He et al., 2015]
self.reduce_low = nn.Sequential(
    nn.Conv2d(64 + 256 + 512, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.PReLU(),
    nn.Conv2d(256, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.PReLU(),
    nn.Conv2d(256, 256, kernel_size=1), nn.BatchNorm2d(256), nn.PReLU()
)
```
![PRuLU](https://img-blog.csdn.net/20160508143448263)
3. 使用最后的第4/5阶段的输出特征图上采样拼接后卷积获得高级融合特征
![image](https://user-images.githubusercontent.com/16298490/50723524-fe4fad80-1119-11e9-9454-76ce5a4285a3.png)
```python
self.reduce_high = nn.Sequential(
    nn.Conv2d(1024 + 2048, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.PReLU(),
    nn.Conv2d(256, 256, kernel_size=3, padding=1), nn.BatchNorm2d(256), nn.PReLU(),
    _ASPP(256)
)
```
4. 从高级融合特征中预测初始显著性图(S0), 然后开始进入一系列的RRBs结构中进行迭代
![image](https://user-images.githubusercontent.com/16298490/50723584-a9606700-111a-11e9-9f53-96624f86d6c9.png)
5. 在最终的输出作为最终的显著性图预测

**Comment by lartpang** [comment]
![image](https://user-images.githubusercontent.com/26847524/50738523-e9554600-120f-11e9-94bd-e580d8f9e898.png)

**Comment by lartpang** [comment]
![image](https://user-images.githubusercontent.com/26847524/50738532-fe31d980-120f-11e9-9114-5a41d0380b27.png)
